# Global variables.
face_object = None
mines_counter_object = None
clock_object = None
photo = None
current_list_of_buttons = None
current_page = None
is_clock_work = False
permission_to_play_one_sound = False
images = {}
rows = 0
columns = 0
time = 0
mines_number = 0
flags_number_left = 0
number_guessed_mines = 0
